#pragma once

#define DISABLE_CALIBRATION 0
#define DISABLE_MAGNETOMETER 1
#define MAGNETOMETER_BLOCKING_MODE 1
#define FIXED_AHRS_UPDATE_RATE 1
#define SPEED_MATH 0

#if FIXED_AHRS_UPDATE_RATE
#define AHRS_UPDATE_RATE 100 // Hz
#endif